In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [11]:
df.sample(10)

age  gender  fever   cough       city has_covid
53   83    Male   98.0    Mild      Delhi       Yes
70   68  Female  101.0  Strong      Delhi        No
56   71    Male    NaN  Strong    Kolkata        No
30   15    Male  101.0    Mild      Delhi       Yes
42   27    Male  100.0    Mild      Delhi       Yes
90   59  Female   99.0  Strong      Delhi        No
65   69  Female  102.0    Mild  Bangalore        No
27   33  Female  102.0  Strong      Delhi        No
85   16  Female  103.0    Mild  Bangalore       Yes
89   46    Male  103.0  Strong  Bangalore        No

In [7]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [14]:
X_train

age  gender  fever   cough       city
51   11  Female  100.0  Strong    Kolkata
2    42    Male  101.0    Mild      Delhi
84   69  Female   98.0  Strong     Mumbai
95   12  Female  104.0    Mild  Bangalore
67   65    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
6    14    Male  101.0  Strong  Bangalore
73   34    Male   98.0  Strong    Kolkata
0    60    Male  103.0    Mild    Kolkata
19   42  Female    NaN  Strong  Bangalore
33   26  Female   98.0    Mild    Kolkata

[80 rows x 5 columns]

In [16]:
y_train

51    Yes
2      No
84     No
95     No
67     No
     ... 
6      No
73    Yes
0      No
19    Yes
33     No
Name: has_covid, Length: 80, dtype: object

# Manual

In [18]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [19]:
X_train_fever

array([[100.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [101.        ],
       [ 99.        ],
       [ 99.        ],
       [103.        ],
       [100.71830986],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [103.        ],
       [100.71830986],
       [103.        ],
       [102.        ],
       [100.        ],
       [100.        ],
       [103.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [104.        ],
       [102.        ],
       [ 99.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [100.71830986],
       [101.        ],
       [103.        ],
       [100.        ],
       [100.71830986],
       [104

In [21]:
# OridnalEncoding -> cough
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# the test data
X_test_cough = oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

In [22]:
X_train_cough

array([[1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],

In [24]:
#  OneHotEncoding -> gender, city
ohe = OneHotEncoder(drop="first", sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

# the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender', 'city']])

X_train_gender_city.shape

(80, 4)

In [25]:
X_train_gender_city

array([[0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],


In [26]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender', 'fever', 'cough', 'city']).values

# the test data
X_test_age = X_test.drop(columns=['gender', 'fever', 'cough', 'city']).values

In [27]:
X_train_age

array([[11],
       [42],
       [69],
       [12],
       [65],
       [19],
       [66],
       [60],
       [69],
       [34],
       [71],
       [16],
       [59],
       [75],
       [ 5],
       [51],
       [11],
       [31],
       [48],
       [79],
       [50],
       [33],
       [13],
       [10],
       [83],
       [17],
       [47],
       [65],
       [ 6],
       [82],
       [49],
       [10],
       [64],
       [73],
       [51],
       [55],
       [81],
       [64],
       [20],
       [15],
       [73],
       [ 5],
       [23],
       [42],
       [25],
       [27],
       [84],
       [74],
       [16],
       [64],
       [19],
       [83],
       [14],
       [49],
       [69],
       [47],
       [81],
       [24],
       [54],
       [19],
       [18],
       [20],
       [75],
       [27],
       [24],
       [72],
       [83],
       [27],
       [71],
       [38],
       [23],
       [80],
       [ 5],
       [80],
       [25],
       [14],
       [34],

In [28]:
X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis=1)

# the test data
X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis=1)

X_train_transformed.shape

(80, 7)

In [44]:
X_train_transformed

array([[ 11.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 42.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 69.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 12.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 65.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 66.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 60.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 69.        , 103.        ,   0.        ,   0.        ,
          1.    

# using column_transformer

In [45]:
from sklearn.compose import ColumnTransformer

In [49]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
  ], remainder="passthrough")


In [51]:
transformer.fit_transform(X_train).shape

(80, 7)

In [52]:
transformer.fit_transform(X_test).shape

(20, 7)

In [46]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=True)
data = [['red'], ['blue'], ['green']]
encoded = encoder.fit_transform(data)

print(encoded)


# This means:

# (0,2) 1.0 → First sample (index 0) has a 1.0 at column 2
# (1,0) 1.0 → Second sample (index 1) has a 1.0 at column 0
# (2,1) 1.0 → Third sample (index 2) has a 1.0 at column 1

  (0, 2)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
